### ISSUE TITLE
OpenCover doesn't reliably work with nunit with (current) default parameters

### ISSUE THREAD

**Issue by timotei** [Ullink/gradle-opencover-plugin#1]
I have investigated an odd functionality, in which, some assemblies tested by nunit via opencover got and other didn't get their coverage computed.

The ones for which coverage wasn't computed, it seems that it is due to "MissingPdb". At the end of the OpenCover run phase, it was printing:

```
Committing...
No results - no assemblies that matched the supplied filter were instrumented
    this could be due to missing PDBs for the assemblies that match the filter
    please review the output file and refer to the Usage guide (Usage.rtf)
```

Now, it seems there were other people that encountered this situation [0], [1], [2], [3](some issues opened on OpenCover's side).

I've tested with multiple options and we need to do the following:
- Add the `-oldstyle` flag for OpenCover - this affects only the way the analysis is done (this flag doesn't support Silverlight apps, but I think we don't care for that. Anyway, we can put that as a configuration on the opencover plugin to allow opt-in for it)
- One of the two:
  - Provide the `/noshadow` argument to NUnit (this is a bit more cumbersome to do I think)
  - Properly set the `/targetdir` parameter for OpenCover to point to the build directories of the test assemblies, not the build directory for the gradle project (e.g: instead of `root/build` use `root/test/bin/Release`

I will do the fix, after we agree which way we should take :)

[0] - http://w3facility.org/question/nunit-tests-failing-within-opencover/
[1] - https://github.com/OpenCover/opencover/issues/119
[2] - https://github.com/OpenCover/opencover/issues/88
[3] - https://github.com/OpenCover/opencover/issues/259

**Comment by gluck** [comment]
Given [this](https://github.com/OpenCover/opencover/blob/8d4f86248c647e9435b6b29fc5ee127e7b0b2f20/main/OpenCover.Framework/Symbols/CecilSymbolManager.cs#L54) the dll folder is (logically if you ask me) the first place opencover looks for the pdb file.

Now as far as I understood, NUnit (when using shadow mode) does copy the PDB there, albeit not reliably enough that OpenCover can grab it (to be confirmed ?).

IMO the fix should be that NUnit starts getting reliable about its PDB file copying.

Though this asks the question of why do we copy those files around at all, and is it the right thing to do ?

**Comment by adrianrus** [comment]
Hello, 

I have the same issue but only after the project is compiled in framework 4.0, perhaps the issues are related and the message perhaps missleading....

I've attempted to make nunit use framework 4.0 with: 

`opencover {
    targetExecArgs='/framework:net-4.0'
}`

but then I got into another situation: 

```
* What went wrong:
Execution failed for task ':opencover'.
> No signature of method: java.lang.String.join() is applicable for argument types: (java.lang.String) values: [ ]
Possible solutions: find(java.lang.String), count(java.lang.String), wait(), trim(), find(), wait(long)
```

**Comment by cornelmarian** [comment]
Hello,

The same issue adrianrus mentioned, only when compiled in fmk 4.0

**Comment by adrianrus** [comment]
For me no longer reproduces with latest version, could be fixed.

**Comment by ngyukman** [comment]
closing as obsolete
