### ISSUE TITLE
Unable to get results from gradle/opencover

### ISSUE THREAD

**Issue by hfickes** [Ullink/gradle-opencover-plugin#17]
I'm not getting any results from opencover.  My nunit tests all run and pass, just no coverage results.

The CodeCoverage.xml file contains a group of lines like the following which indicate that the plugin is telling opencover to filter out the DLLs we are trying to measure.

```
Module hash="A3-F0-3A-1A-FF-38-D7-EF-A2-55-C9-8B-84-37-CF-CF-00-80-70-23" skippedDueTo="Filter">
<FullName>C:\gitlab-runner\builds\83ebc972\0\active\scrpt\output\Scrpt.Core.dll</FullName>
<ModuleName>Scrpt.Core</ModuleName>
<Classes/>
```

which has the correct path for the dll file, but I don't see why it is skipped due to filtering.  The unit tests are contained in a dll called Scrpt.Test.dll and the rest of the code is in other DLLs which are all filtered out.

I'm using the following plugins

plugins {
 id 'com.ullink.msbuild' version '2.15'
 id 'com.ullink.nunit' version '1.8'
 id 'com.ullink.opencover-nunit' version '1.6'
}

and the plugin definitions for nunit and opencover are:

nunit {
  testAssemblies = [file('output/Scrpt.Tests.dll')]
  shadowCopy = false
  useX86 = true
  ignoreFailures = false
}

opencover {
  targetAssemblies = [file('output/Scrpt.dll'),file('output/Scrpt.Core.dll'),file('output/Scrpt.SourceCitations.dll'),file('output/ScrptUtilLib.dll')]
  ignoreFailures = false
}

Thank you for your help,
-herb

**Comment by adrianrus** [comment]
Hi, 

I think for the targetAssemblies you need a list of strings not file objects:

**Comment by hfickes** [comment]
Thank you.  I changed it to just strings but it didn't make any difference.

**Comment by hfickes** [comment]
Looking at the code, and I've never worked with groovy before, it appears that anything added to the targetAssemblies is also filtered out of the results.  I must be wrong, but here is the code in question.

It looks like line 77 of OpenCover.groovy should have a **+** in front of the filter:\\ and not a **-**

```
        commandLineArgs += ["-target:${getTargetExec()}", "\"-targetargs:${getTargetExecArgs().collect({escapeArg(it)}).join(' ')}\"", "-targetdir:${project.buildDir}"]
        def filters = getTargetAssemblies().collect { "+[${FilenameUtils.getBaseName(project.file(it).name)}]*" }
        commandLineArgs += '-filter:\\"' + filters.join(' ') + '\\"'
```

(Edited a day later...  My comment about line 77 is incorrect,.  The code in OpenCover.grooby appears to be correct.  My comment about replacing - with + was confusing the filter contents with the switch name "-filter".)

**Comment by gluck** [comment]
Running gradle with `--info` (or is it `--debug`) should give you the command-line used for opencover execution and you should be able to check the filters.
AFAICT you should get something like `-filter:"+[Scrpt]"` which means "include code from this lib" (I think)

**Comment by hfickes** [comment]
@gluck , thanks for the help with the command line.  You are correct about the filters, that should work and I still don't know why it doesn't.

I ended up replacing using the opencover plugin with a task that does the same thing.  Not sure why the plugin didn't work, but the replacement is essentially the same thing in that it calls nunit, creates the output coverage xml which sonarqube then uploads.

A bit awkward, but it works.

```
task opencover(type:Exec) {
 executable 'C:\\Program Files (x86)\\OpenCover\\OpenCover.Console.exe'
 workingDir file('output')
 args "-target:c:\\Program Files (x86)\\NUnit 2.6.4\\bin\\nunit-console-x86.exe", "-targetargs:c:\\gitlab-runner\\builds\\83ebc972\\0\\active\\scrpt\\output\\scrpt.tests.dll /noshadow", '-output:coverage.xml', '-filter:+[*]*'
}

```

**Comment by ngyukman** [comment]
closing as obsolete
