### ISSUE TITLE
Error when parsing arguments sent to NUnit

### ISSUE THREAD

**Issue by adrianrus** [Ullink/gradle-opencover-plugin#2]
i.e. with plugin configuration:

`opencover {
    targetExecArgs='/noshadow'
}`

output: 

> Execution failed for task ':opencover'.
> No signature of method: java.lang.String.join() is applicable for argument types: (java.lang.String) values: [ ]
> Possible solutions: find(java.lang.String), count(java.lang.String), wait(), trim(), find(), wait(long)

**Comment by muryoh** [comment]
Hi Adrian,

targetExecArgs is (albeit secretly ;) ) expecting a list of arguments
Can you try with targetExecsArgs=['/noshadow']?

Cheers,
Rémy

**Comment by muryoh** [comment]
Closing as I don't think it was an actual problem. Please reopen if necessary!
