### ISSUE TITLE
OpenCover download location is outdated

### ISSUE THREAD

**Issue by laurensknoll** [Ullink/gradle-opencover-plugin#3]
Hi,

Thanks for the plugin. It works wonderful. However I'm unable to download the latest versions of opencover, because the repository has been moved to GitHub: https://github.com/opencover/opencover/releases

Is it possible to update the download URL in the plugins "downloadOpenCover"-method?

``` groovy
File downloadOpenCover(Project project, String version) {
        def dest = new File(new File(project.gradle.gradleUserHomeDir, 'caches'), 'opencover')
        if (!dest.exists()) {
            dest.mkdirs()
        }
        def ret = new File(dest, "opencover-${version}")
        if (!ret.exists()) {
            project.logger.info "Downloading & Unpacking OpenCover ${version}"
            def tmpFile = File.createTempFile("opencover.zip", null)
            new URL(https://bitbucket.org/shaunwilde/opencover/downloads/opencover.${version}.zip").withInputStream { i ->
                tmpFile.withOutputStream {
                    it << i
                }
            }
            project.ant.unzip(src: tmpFile, dest: ret)
        }
        ret
    }
```

Regards,
Laurens

**Comment by muryoh** [comment]
Hi Laurens,

It sounds like a good idea :+1: 
Maybe the default version should be updated in the process too.

**Comment by muryoh** [comment]
Looks like https://github.com/Ullink/gradle-opencover-plugin/pull/4 covers that :)

**Comment by muryoh** [comment]
Version 1.2 was released and fixes it.

Cheers!
