### ISSUE TITLE
Opencover does not return coverage

### ISSUE THREAD

**Issue by sakrai** [Ullink/gradle-opencover-plugin#7]
Hi,

I am not sure what I am doing wrong but through the command line I can get my coverage to produce the required results, however, via my gradle.build file can't see nothing, when I run **gradle opencover**. Please see the results below:

:msbuild
  Bank -> C:\Users\sak\Documents\Visual Studio 2015\Projects\gradlesol\Bank\bin\Debug\Bank.dll
  BankTests -> C:\Users\sak\Documents\Visual Studio 2015\Projects\gradlesol\BankTests\bin\Debug\BankTests.dll
:opencover UP-TO-DATE

BUILD SUCCESSFUL

Total time: 10.09 secs

**gradle.build** file below:

plugins {
  id 'com.ullink.msbuild' version '2.14'
  id 'com.ullink.nunit' version '1.4'
  id "com.ullink.opencover-nunit" version "1.3"
}

archivesBaseName = 'Bank'

msbuild {
  solutionFile = file('gradlesol.sln')
  projectName = 'Bank'
}

nunit {
   nunitVersion = '2.6.4'
   testAssemblies = [ msbuild.projects['BankTests'].properties.TargetPath ]
}
nunit.dependsOn msbuild

opencover {
    targetExec=file('Projects/gradlesol/packages/NUnit.Runners.Net4.2.6.4/tools/nunit-console.exe')
    targetExecArgs = ['/noshadow', '/nologo']
    targetAssemblies=['\BankTests\bin\Debug\BankTests.dll']
}
opencover.dependsOn msbuild

**Comment by gluck** [comment]
First when using this plugin together with `nunit` one, you don't need to define `targetExec` and `targetExecArgs`, they are [inferred](https://github.com/Ullink/gradle-opencover-plugin/blob/master/src/main/groovy/com/ullink/gradle/opencover/OpenCoverNUnitPlugin.groovy#L20) from nunit task.

The task inputs are [just your test assembly](https://github.com/Ullink/gradle-opencover-plugin/blob/master/src/main/groovy/com/ullink/gradle/opencover/OpenCover.groovy#L20) (maybe not rightly so), hence it will be "UP-TO-DATE" as long as the test assembly hasn't been rebuilt. Looks like in your case they are, so maybe you test assembly path is incorrect ? (not sure it's checked)

**Comment by sakrai** [comment]
It is correct that the **targetAssemblies** is suppose to point to the dll file? As I have in my **gradle.build** file above? I still can't get it working, I have attached the output while running gradle opencover with debug option. Will appreciate your help... 

[output from run.txt](https://github.com/Ullink/gradle-opencover-plugin/files/242525/output.from.run.txt)

**Comment by gluck** [comment]
again, the task is skipped coz up-to-date:

```
Skipping task ':opencover' as it is up-to-date
```

Running clean first may give you more details on why it's not working.

**Comment by sakrai** [comment]
Thanks, I managed to get pass that error. I now get the below message, I am not sure why "File type not known: Studio" is mentioned, any ideas why it could be failing? Thanks

```
:msbuild
  Bank -> C:\Users\sak\Documents\Visual Studio 2015\Projects\gradlesol\Bank\bin\Debug\Bank.dll
  BankTests -> C:\Users\sak\Documents\Visual Studio 2015\Projects\gradlesol\BankTests\bin\Debug\BankTests.dll
:opencover
Executing: C:\Users\sak\.gradle\caches\nunit\NUnit-2.6.4\bin\nunit-console.exe
NUnit-Console version 2.6.4.14350
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment -
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 2.0.50727.8689 ( Net 3.5 )

File type not known: Studio
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
:opencover FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':opencover'.
> Process 'command 'C:\Users\sak\.gradle\caches\opencover\opencover-4.6.166\OpenCover.Console.exe'' finished with non-zero exit value -1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by gluck** [comment]
As the log says :smile: 

> Run with --info or --debug option to get more log output

**Comment by sakrai** [comment]
I have found my issue: The problem lies in the path - if there are spaces in the absolute path it will bark with the above error as it didn’t like the spaces in folder **Visual Studio** > **C:\Users\sak\Documents\Visual Studio 2015\**. I didn’t use absolute paths here. Once I moved the project to the documents folder, the build executed successfully :)

Is there a way this could be detected and omitted in the code base…

Thanks for your help :+1:

**Comment by gluck** [comment]
Good, do you know what was the command line run and what arg was incorrectly escaped ?

**Comment by sakrai** [comment]
My current directory path from executing _**gradle opencover**_ was _C:\Users\sak\Documents\Visual Studio 2015\Projects\gradlesol_  My task was written out in the below two ways and both produced the below error. The same paths work with the nunit plugin. I have also attached a file which contains the output when executing with info

:

opencover {
    targetAssemblies = [ msbuild.projects['BankTests'].properties.TargetPath ]
}

opencover {
    targetAssemblies = ['BankTests/bin/Debug/BankTests.dll']
}

```
PS C:\Users\sak\Documents\Visual Studio 2015\Projects\gradlesol> gradle opencover
:msbuild
  Bank -> C:\Users\sak\Documents\Visual Studio 2015\Projects\gradlesol\Bank\bin\Debug\Bank.dll
  BankTests -> C:\Users\sak\Documents\Visual Studio 2015\Projects\gradlesol\BankTests\bin\Debug\BankTests.dll
:opencover
Executing: C:\Users\sak\.gradle\caches\nunit\NUnit-2.6.4\bin\nunit-console.exe
NUnit-Console version 2.6.4.14350
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment -
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 2.0.50727.8689 ( Net 3.5 )

File type not known: Studio
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
:opencover FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':opencover'.
> Process 'command 'C:\Users\sak\.gradle\caches\opencover\opencover-4.6.166\OpenCover.Console.exe'' finished with non-zero exit value -1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 20.266 secs

```

[info.txt](https://github.com/Ullink/gradle-opencover-plugin/files/246631/info.txt)
